name: volt
description: A refactored running app

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management
  flutter_riverpod: ^2.6.0
  riverpod_annotation: ^2.4.0
  
  # Navigation
  auto_route: ^10.0.1
  
  # Services
  permission_handler: ^12.0.0+1
  flutter_blue_plus: ^1.31.13
  geolocator: ^14.0.0
  sensors_plus: ^6.1.1
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2
  
  # Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2+1
  path_provider: ^2.1.2
  path: ^1.8.3
  
  # UI Components
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  google_maps_flutter: ^2.5.3
  fl_chart: ^0.71.0
  
  # Audio
  just_audio: ^0.10.2
  audio_session: ^0.2.1
  flutter_tts: ^4.2.2
  
  # GPX and Activity Data
  gpx: ^2.2.1
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.3.3
  http: ^1.1.2
  share_plus: ^11.0.0
  vibration: ^3.1.3
  wakelock_plus: ^1.1.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  auto_route_generator: ^10.0.1
  riverpod_generator: ^2.6.5
  mockito: ^5.4.5
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
